### ISSUE TITLE
[BUG]no devices/emulators found

### ISSUE THREAD

**Issue by Apurva-2003** [srevinsaju/guiscrcpy#155] opened 2020-08-01 13:01 UTC
Hi,
I have been using scrcpy for a long time now and was working fine on my Ubuntu 18.04 LTS.
However after installing guiscrcpy through snap I am getting this error.

$guiscrcpy.scrcpy
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1

My phone is connected with usb debigging enabled. I have tried reinstalling scrcpy and guiscrcpy and also removing scrcpy as mention in an other issue. On reinstalling, scrcpy again starts working until I open guiscrcpy and then  this error again starts coming.

**Comment by srevinsaju** [comment] 2020-08-01 15:21
@Apurva-2003 can you please show me the output of 
```
guiscrcpy.adb devices -l
```

**Comment by Apurva-2003** [comment] 2020-08-01 16:08
Hi,
This is the output
$ guiscrcpy.adb devices -1
adb: usage: adb devices [-l]

Are these some kind of magic words because you always ask this in issues.
Before running them I again uninstalled scrcpy and gui. Then reinstalled scrcpy and my phone was working over it. Then I install gui and same error again started coming.

**Comment by srevinsaju** [comment] 2020-08-01 16:10
Oops. not `-1`, its `-l`, l for *lad*, can you show me the output of 
```bash
guiscrcpy.adb devices -l
```

It helps to find if `adb` is able to detect your device. if not, its not a bug with `scrcpy` / `guiscrcpy`.

**Comment by Apurva-2003** [comment] 2020-08-01 16:14
$ guiscrcpy.adb devices -l
List of devices attached

It is not showing the device

**Comment by srevinsaju** [comment] 2020-08-01 16:14
Hmm. can you show me the output of  `sudo snap connections guiscrcpy` ?

**Comment by Apurva-2003** [comment] 2020-08-01 16:15
`Interface        Plug                       Slot             Notes
adb-support      guiscrcpy:adb-support      -                -
content          guiscrcpy:adb              -                -
desktop          guiscrcpy:desktop          :desktop         -
desktop-legacy   guiscrcpy:desktop-legacy   :desktop-legacy  -
home             guiscrcpy:home             :home            -
network          guiscrcpy:network          :network         -
network-bind     guiscrcpy:network-bind     :network-bind    -
opengl           guiscrcpy:opengl           :opengl          -
process-control  guiscrcpy:process-control  -                -
unity7           guiscrcpy:unity7           :unity7          -
wayland          guiscrcpy:wayland          :wayland         -
x11              guiscrcpy:x11              :x11             -
`

**Comment by srevinsaju** [comment] 2020-08-01 16:16
`sudo snap connect guiscrcpy:adb` and `sudo snap connect adb-support`

**Comment by Apurva-2003** [comment] 2020-08-01 16:17
apurva@apurva-mishra:~$ sudo snap connect guiscrcpy:adb
error: snap "core" has no "content" interface slots
apurva@apurva-mishra:~$ sudo snap connect adb-support
error: cannot resolve connection, plug snap name is empty

**Comment by Apurva-2003** [comment] 2020-08-01 16:18
`apurva@apurva-mishra:~$ sudo snap connect guiscrcpy:adb
error: snap "core" has no "content" interface slots
apurva@apurva-mishra:~$ sudo snap connect adb-support
error: cannot resolve connection, plug snap name is empty
apurva@apurva-mishra:~$ 
`

**Comment by srevinsaju** [comment] 2020-08-01 16:19
```bash
sudo snap connect guiscrcpy:adb :adb
sudo snap connect guiscrcpy:adb-support :adb-support
```

**Comment by Apurva-2003** [comment] 2020-08-01 16:21
`apurva@apurva-mishra:~$ sudo snap connect guiscrcpy:adb :adb
error: snap "core" has no slot named "adb"
apurva@apurva-mishra:~$ sudo snap connect guiscrcpy:adb-support :adb-support
`
It ended after running some process

**Comment by srevinsaju** [comment] 2020-08-01 16:21
Now try again, it should work now

**Comment by Apurva-2003** [comment] 2020-08-01 16:26
Through the interface it connects but screen of phone does not show
Then I tried this from other issue but ..
`$ guiscrcpy.scrcpy
INFO: scrcpy 1.14 <https://github.com/Genymobile/scrcpy>
/snap/guiscrcpy/202/usr/local/share/sc...shed. 2.0 MB/s (27694 bytes in 0.013s)
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: The server version (1.13) does not match the client (1.14)
	at com.genymobile.scrcpy.Server.createOptions(Server.java:78)
	at com.genymobile.scrcpy.Server.main(Server.java:176)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:287)
apurva@apurva-mishra:~$ apurva@apurva-mishra:~$ sudo snap connect guiscrcpy:adb `

**Comment by srevinsaju** [comment] 2020-08-01 16:27
@Apurva-2003 Try `guiscrcpy` instead of `guiscrcpy.scrcpy`

**Comment by Apurva-2003** [comment] 2020-08-01 16:30
You got me wrong.
Through guiscrcpy which has gui interface I can see my device but on connecting only toolbars show the screen does not show up. then I tried to use  guiscrcpy.scrcpy

**Comment by srevinsaju** [comment] 2020-08-01 16:32
Yes, you are right. It will not show up. Because there is no `GUI` while running `guiscrcpy.scrcpy`. Its the plain old `scrcpy`

I guess, if it does not work, try the appimage perhaps?

**Comment by Apurva-2003** [comment] 2020-08-01 16:36
Thank for your help I will try app image but do not have high hopes as scrcpy was working fine . It is only after installing guiscrcpy that I got this error. In fact I also use adb for droidcam and it also working fine. I will try the app image tomorrow and update in the thread.

**Comment by Apurva-2003** [comment] 2020-08-02 11:56
*Update
The Appimage is working fine. I think there is some error with the snap.

**Comment by srevinsaju** [comment] 2020-08-02 15:50
I am migrating to Appimages, snaps are not a good way to run things, Snaps are only too popular :smile:

closing this issue.

**Closed by srevinsaju** 2020-08-02 15:50 UTC
Labels: bug
