### ISSUE TITLE
[FR] SNDCPY implementation

### ISSUE THREAD

**Issue by Netherquark** [srevinsaju/guiscrcpy#190] opened 2020-10-12 09:38 UTC
Could you bring support for [SNDCPY ](https://github.com/rom1v/sndcpy)_with_ SCRCPY? Its a pain to get SNDCPY working on Windows, so it would be great if you could implement a side by side solution for both.

**Comment by srevinsaju** [comment] 2020-10-12 09:42
Duplicate of #148

**Closed by srevinsaju** 2020-10-12 09:42 UTC
Labels: enhancement, feature, feature_request
