### ISSUE TITLE
import qdarkstyle Error.  

### ISSUE THREAD

**Issue by mitcoes** [srevinsaju/guiscrcpy#38] opened 2019-12-11 14:36 UTC
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/guiscrcpy/__main__.py", line 23, in <module>
    import qdarkstyle
ModuleNotFoundError: No module named 'qdarkstyle'

Using Manjaro, and installing from AUR in both packages.

**Comment by srevinsaju** [comment] 2019-12-14 11:23
use ``` pip3 install qdarkstyle ```

**Comment by yochananmarqos** [comment] 2019-12-14 15:14
@mitcoes: I can't reproduce that. Have you reubilt `python-qdarkstyle`? 

@srevinsaju That's not how it works on Arch. Python packages are available to install from the repos. Everything should be installed with Pacman, otherwise there could be conflicting files installing with something else. Unless one does development, there's never a reason to use `pip` to install Python packages. In that case, they should be installed in a virtual environment.

**Comment by srevinsaju** [comment] 2019-12-14 15:19
@yochananmarqos, thanks for the info, I hope its not a problem with guiscrcpy git branch; I am so confused with Arch Linux and how it works, thanks for making a AUR package for delivering guiscrcpy to Arch :+1:

**Comment by srevinsaju** [comment] 2020-01-16 10:43
Closing this

**Closed** 2020-01-16 10:43 UTC
